name: platformio build

on:
  push:
    branches: ["*"]
    paths-ignore: ["*.md"]
  pull_request:
    branches: ["*"]
    paths-ignore: ["*.md"]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Check
        run: |
          platformio check
      - name: Build
        run: |
          platformio run
